In [211]:
#Importing numpy(np alias)
import numpy as np

In [212]:
#Basic 1D ndarray init
oneDimArr = np.array([4,6,8,2])
print(oneDimArr)

#You can pass any iterable(list, tuple) to np.array() method and it will create a ndarray object
oneDimArrSample = np.array((5,2,7,9,2))
print(oneDimArrSample)

[4 6 8 2]
[5 2 7 9 2]


In [213]:
#Basic 2D array init
twoDimArr = np.array([[5.7,2.4,2.5],[8.3,4.6,1.2]])
print(twoDimArr)

[[5.7 2.4 2.5]
 [8.3 4.6 1.2]]


In [214]:
#Number of dimentions of ndarray
print(oneDimArr.ndim)
print(oneDimArrSample.ndim)
print(twoDimArr.ndim)

1
1
2


In [215]:
#Shape gives number of rows, columns or depth of ndarray
threeDimArr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(threeDimArr)
print(threeDimArr.ndim)

print(oneDimArr.shape)
print(twoDimArr.shape)
print(threeDimArr.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(4,)
(2, 3)
(3, 2, 2)


In [216]:
#Datatype of each element of ndarray
print(oneDimArr.dtype)
print(twoDimArr.dtype)
print(threeDimArr.dtype)

int32
float64
int32


In [217]:
#Size of each element of ndarray in bytes
print(oneDimArr.itemsize)
print(twoDimArr.itemsize)
print(threeDimArr.itemsize)

4
8
4


In [218]:
#Number of elements of ndarray
print(oneDimArr.size)
print(twoDimArr.size)
print(threeDimArr.size)

4
6
12


In [219]:
#Total bytes consumed by ndarray
print(oneDimArr.itemsize * oneDimArr.size)
print(twoDimArr.itemsize * twoDimArr.size)
print(threeDimArr.itemsize * threeDimArr.size)

#Similar way to find total bytes consumes by ndarray
print(oneDimArr.nbytes)
print(twoDimArr.nbytes)
print(threeDimArr.nbytes)

16
48
48
16
48
48


In [220]:
#ndarray indexing

#Get a specific array element in 1D ndarray
oneDimArrayIndexing = np.array([3,5,8,1,9,0])
print(oneDimArrayIndexing[4])

#Get a specific array element in 2D ndarray
twoDimArrayIndexing = np.array([[5,2,8,14],[3,10,12,70]])
print(twoDimArrayIndexing[1,2])

#Get a specific array element in 3D ndarray
threeDimArrayIndexing = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(threeDimArrayIndexing[1,1,0])

9
12
7


In [221]:
#ndarray negative indexing

# 1D ndarray negative indexing
# [3, 5, 8, 1, 9, 0]
#  0  1  2  3  4  5
# -6 -5 -4 -3 -2 -1
print(oneDimArrayIndexing[-1])
print(oneDimArrayIndexing[-2])
print(oneDimArrayIndexing[-3])
print(oneDimArrayIndexing[-4])
print(oneDimArrayIndexing[-5])
print(oneDimArrayIndexing[-6])

#Similarly we can negative index 2D ndarray
print(twoDimArrayIndexing[-2,-4])
print(twoDimArrayIndexing[-1,-3])

#Similarly we can negative index 3D ndarray
print(threeDimArrayIndexing[-2,-1,-2])
print(threeDimArrayIndexing[-3,-2,-1])

0
9
1
8
5
3
5
10
7
2


In [222]:
#Indexing in a range, [r:c) where r is included and c is excluded.
print(oneDimArrayIndexing[1:4])
print(twoDimArrayIndexing[-1, 1:])
print(twoDimArrayIndexing[-2, :3])

[5 8 1]
[10 12 70]
[5 2 8]


In [223]:
#Indexing in a range with step
sampleIterating1DArray = np.array([4,7,8,11,35,73,224,67,24,688,52,97,56,571,89,23,84,274])
print(sampleIterating1DArray[2:11:2])
print(sampleIterating1DArray[2:15:3])
print(sampleIterating1DArray[2:-1:4])

[  8  35 224  24  52]
[ 8 73 24 97 89]
[  8 224  52  89]


In [224]:
#Changing value of element of 1D array using indexing
sampleIterating1DArray[2]=100
print(sampleIterating1DArray)

sampleIterating1DArray[5:8] = -5
print(sampleIterating1DArray)

twoDimArrayIndexing[1,2] = 101
print(twoDimArrayIndexing)

twoDimArrayIndexing[:,1] = [99,102]
print(twoDimArrayIndexing)

[  4   7 100  11  35  73 224  67  24 688  52  97  56 571  89  23  84 274]
[  4   7 100  11  35  -5  -5  -5  24 688  52  97  56 571  89  23  84 274]
[[  5   2   8  14]
 [  3  10 101  70]]
[[  5  99   8  14]
 [  3 102 101  70]]


In [225]:
#Initializing different types of ndarray
allZeroArray = np.zeros(shape=(4,6), dtype='int8')
print(allZeroArray)

allOneArray = np.ones(shape=(6,3), dtype='int8')
print(allOneArray)

#Array filled for a specific number
allFilledArray = np.full((2,3,6), 74.28, dtype='float64')
print(allFilledArray)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[[74.28 74.28 74.28 74.28 74.28 74.28]
  [74.28 74.28 74.28 74.28 74.28 74.28]
  [74.28 74.28 74.28 74.28 74.28 74.28]]

 [[74.28 74.28 74.28 74.28 74.28 74.28]
  [74.28 74.28 74.28 74.28 74.28 74.28]
  [74.28 74.28 74.28 74.28 74.28 74.28]]]


In [226]:
#Same as np.like() we can create same value filled ndarray using np.full_like() in which we pass ndarray and the value to be filled so that the same shapped ndarray can be created using the value passed
allOneAlikeShappedArray = np.full_like(allOneArray, 7)
print(allOneAlikeShappedArray)

allZeroAlikeShappedArray = np.full_like(allZeroArray, 4)
print(allZeroAlikeShappedArray)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [227]:
#Creating ndarray from random numbers
randomElementArray = np.random.rand(2,5,9)
print(randomElementArray)

[[[0.67196073 0.72512795 0.39835487 0.5341577  0.55278503 0.55409097
   0.21273318 0.76445503 0.64069932]
  [0.64200939 0.62142627 0.62452127 0.98620796 0.94946146 0.2871165
   0.38363566 0.27520282 0.04430918]
  [0.17136991 0.22244748 0.43423159 0.06082455 0.49309566 0.93620401
   0.64384115 0.82204214 0.37235585]
  [0.94322985 0.04853991 0.67911752 0.61959227 0.20889994 0.78336413
   0.77308907 0.92149654 0.96094775]
  [0.03795385 0.33916335 0.38616056 0.99888718 0.5914371  0.94320093
   0.59693733 0.43571493 0.80746126]]

 [[0.74266968 0.7182938  0.96463371 0.60427233 0.92793262 0.96452802
   0.71184975 0.34022305 0.22729015]
  [0.08988785 0.52497973 0.56175735 0.06083167 0.13016051 0.79350317
   0.90259688 0.01226193 0.8023194 ]
  [0.38500039 0.56948746 0.43934186 0.49583693 0.91403779 0.73178763
   0.67405771 0.21428776 0.76330588]
  [0.63318782 0.21985633 0.5931548  0.47547273 0.61184069 0.05076688
   0.77845027 0.29079028 0.16735428]
  [0.56748759 0.0040977  0.96440319 0.5513446

In [228]:
#Creating random ndarray from shape of another ndarray
randomElementArrayFromShape = np.random.random_sample(threeDimArrayIndexing.shape)
print(randomElementArrayFromShape)

[[[0.41066865 0.34210619]
  [0.44617289 0.59556005]]

 [[0.80307066 0.51353093]
  [0.02106015 0.51378416]]

 [[0.32209385 0.35218306]
  [0.88696432 0.28590664]]]


In [229]:
#Creating random integer ndarray, np.random.randint(endRange, size), endRange is excluded
randomIntegerArray = np.random.randint(8, size=(5,6))
print(randomIntegerArray)

#Creating random integer ndarray, np.random.randint(startRange, endRange, size), startRange is excluded, endRange is excluded
randomIntegerArray = np.random.randint(4 ,8, size=(5,6))
print(randomIntegerArray)

[[5 2 3 6 0 0]
 [2 4 4 7 6 6]
 [0 4 0 3 6 6]
 [5 0 6 5 2 1]
 [6 1 4 7 3 0]]
[[4 7 4 7 4 7]
 [6 5 7 4 5 7]
 [7 6 4 6 6 5]
 [5 4 7 6 4 4]
 [6 5 6 7 5 6]]


In [230]:
#Creating identity ndarray matrix
identityNpArray = np.identity(4, dtype='int8')
print(identityNpArray)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [231]:
#Repeating ndarray on axis=0
sampleNdArray = np.array([[1,5,6,7]])
repeatedSampleArrayAxisZero = np.repeat(sampleNdArray, 4, axis=0)
print(repeatedSampleArrayAxisZero)

#Repeating ndarray on axis=1
sampleNdArray1 = np.array([[1,5,6,7]])
repeatedSampleArrayAxisOne = np.repeat(sampleNdArray1, 4, axis=1)
print(repeatedSampleArrayAxisOne)

[[1 5 6 7]
 [1 5 6 7]
 [1 5 6 7]
 [1 5 6 7]]
[[1 1 1 1 5 5 5 5 6 6 6 6 7 7 7 7]]


In [232]:
#Exercise:
#Create 2d np array using predefined functions discussed ago.
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

oneFilledArray = np.ones((5,5), dtype='int8')
zerofilledArray = np.zeros((3,3), dtype='int8')
zerofilledArray[1,1] = 9
oneFilledArray[1:-1, 1:-1] = zerofilledArray.copy()
print(oneFilledArray)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [233]:
# Copy and view
# View is reference of a ndarray, if you change via one reference then other reference data will be changed
mainRefArray = np.array([4,6,8,9,11])
otherRefArray = mainRefArray
# If you change data via otherRefArray then mainRefArray data will also be changed.
otherRefArray[3] = 100
print(mainRefArray)
print(otherRefArray)

[  4   6   8 100  11]
[  4   6   8 100  11]


In [234]:
# Copy is when you allocate different memory location and copy the content of one array to other array so that the references will be deferent
otherCopyArray = mainRefArray.copy()
otherCopyArray[3] =250
print(mainRefArray)
print(otherRefArray)
print(otherCopyArray)

[  4   6   8 100  11]
[  4   6   8 100  11]
[  4   6   8 250  11]


In [235]:
# Mathematics using numpy
mathNdArray = np.array([4,8,9,2,1,10,12])

# Add constant with each element of ndarray
print(mathNdArray + 3)

# remove constant from each element of ndarray
print(mathNdArray - 4)

# multiply constant from each element of ndarray
print(mathNdArray * 3)

# divide constant from each element of ndarray
print(mathNdArray / 4)

[ 7 11 12  5  4 13 15]
[ 0  4  5 -2 -3  6  8]
[12 24 27  6  3 30 36]
[1.   2.   2.25 0.5  0.25 2.5  3.  ]


In [236]:
#Mathematics of each element of ndarray with another ndarray
mathAddArrayOne = np.array([2,5,8])
mathAddArrayTwo = np.array([6,9,13])

print(mathAddArrayOne + mathAddArrayTwo)
print(mathAddArrayTwo - mathAddArrayOne)
print(mathAddArrayOne * mathAddArrayTwo)
print(mathAddArrayOne / mathAddArrayTwo)

[ 8 14 21]
[4 4 5]
[ 12  45 104]
[0.33333333 0.55555556 0.61538462]


In [237]:
#Power of each elements of ndarray
powerArray = mathNdArray ** 2
print(powerArray)

[ 16  64  81   4   1 100 144]


In [238]:
#Trigonometry with ndarray
trigNdArray = np.array([15,30,60,90,120,150,180,210,240,270,300,360])
print(np.sin(trigNdArray))
print(np.cos(trigNdArray))
print(np.tan(trigNdArray))

[ 0.65028784 -0.98803162 -0.30481062  0.89399666  0.58061118 -0.71487643
 -0.80115264  0.46771852  0.94544515 -0.17604595 -0.99975584  0.95891572]
[-0.75968791  0.15425145 -0.95241298 -0.44807362  0.81418097  0.69925081
 -0.59846007 -0.88387747  0.32578131  0.98438195 -0.02209662 -0.28369109]
[-0.8559934  -6.4053312   0.32004039 -1.99520041  0.71312301 -1.02234624
  1.33869021 -0.52916669  2.90208535 -0.17883906 45.24474207 -3.38014041]


In [239]:
# Matrix multiplication using numpy
# If we are multiplying two matrices of (r1 * c1) and (r2 * c2) dimensions then for valid multiplication c1=r2 condition must be valid. Dimension of final matrix will be (r1,c2)
multMatOne = np.array([[1,2],[3,4],[5,6]]) # dimension -> (3,2)
multMatTwo = np.array([[6,7,8,9],[4,2,3,10]]) # dimension -> (2,4)
multMatResult = np.matmul(multMatOne, multMatTwo) # Final dimension -> (3,4)
print(multMatResult)
print("Dimension:" , multMatResult.shape)

[[ 14  11  14  29]
 [ 34  29  36  67]
 [ 54  47  58 105]]
Dimension: (3, 4)


In [240]:
# Determinant of matrix using numpy
detMat = [[3,6,8],[2,9,1],[7,8,12]]
print(np.linalg.det(detMat))

-177.99999999999997


In [241]:
# Numpy stat
matStat = np.array([[5,6,8,10],[11,1,3,10],[6,5,10,11]])
print(np.max(matStat, axis=0))
print(np.max(matStat, axis=1))
print(np.min(matStat, axis=0))
print(np.min(matStat, axis=1))
print(np.average(matStat, axis=0))
print(np.average(matStat, axis=1))
print(np.sum(matStat, axis=0))
print(np.sum(matStat, axis=1))

[11  6 10 11]
[10 11 11]
[ 5  1  3 10]
[5 1 5]
[ 7.33333333  4.          7.         10.33333333]
[7.25 6.25 8.  ]
[22 12 21 31]
[29 25 32]


In [242]:
# Reorganizing ndarray
# Note: multiplication of individual dimentions must be equal to number of elements in original ndarray
matStat = np.array([[5,6,8,10],[11,1,3,10],[6,5,10,11],[93,12,45,32]])
print(matStat.reshape(2,8))
print(matStat.reshape(8,2))
print(matStat.reshape(2,4,2))
print(matStat.reshape(2,2,2,2))

[[ 5  6  8 10 11  1  3 10]
 [ 6  5 10 11 93 12 45 32]]
[[ 5  6]
 [ 8 10]
 [11  1]
 [ 3 10]
 [ 6  5]
 [10 11]
 [93 12]
 [45 32]]
[[[ 5  6]
  [ 8 10]
  [11  1]
  [ 3 10]]

 [[ 6  5]
  [10 11]
  [93 12]
  [45 32]]]
[[[[ 5  6]
   [ 8 10]]

  [[11  1]
   [ 3 10]]]


 [[[ 6  5]
   [10 11]]

  [[93 12]
   [45 32]]]]


In [243]:
# Vertically stacking ndarrays
vertStackArrOne = np.array([2,5,8,9])
vertStackArrTwo = np.array([9,5,6,1])
vertStackArrThree = np.array([9,10,45,12])
#You can stack any number of ndarrays
stackedArray = np.vstack([vertStackArrOne, vertStackArrTwo, vertStackArrThree])
print(stackedArray)

[[ 2  5  8  9]
 [ 9  5  6  1]
 [ 9 10 45 12]]


In [244]:
# Horizontally stacking ndarrays
horzStackArrOne = np.array([2,5,8,9])
horzStackArrTwo = np.array([9,5,6,1])
horzStackArrThree = np.array([9,10,45,12])
stackedArraySample = np.hstack([vertStackArrOne, vertStackArrTwo, vertStackArrThree])
print(stackedArraySample)

[ 2  5  8  9  9  5  6  1  9 10 45 12]


In [245]:
#Reading data from txt file
fileData = np.genfromtxt('input.txt', delimiter=',')
fileData = fileData.astype('int8')
print(fileData)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [246]:
#Boolean masking
sampleMasking = np.array([[6,8,3,4,5],[8,9,1,3,5],[7,6,1,2,3]])
print(sampleMasking >= 5)
# ~ is not operator
print(~(sampleMasking >= 5))

#We can use boolean masking as index for the ndarray, for those elements for which true are generating will be printed.
print(sampleMasking[sampleMasking>=5])

[[ True  True False False  True]
 [ True  True False False  True]
 [ True  True False False False]]
[[False False  True  True False]
 [False False  True  True False]
 [False False  True  True  True]]
[6 8 5 8 9 5 7 6]


In [247]:
# ndarray can be indexed using ndarray
SampleNdArrayForIndexing = np.array([15,30,60,90,120,150,180,210,240,270,300,360])
indexingArray = np.array([3,7,9,10])
print(SampleNdArrayForIndexing[indexingArray])

[ 90 210 270 300]


In [248]:
#Any vs All
#If any element out of all elements is following given condition then true will be generated
print(np.any(sampleMasking >=5, axis=0))
print(np.any(sampleMasking >=5, axis=1))

#If all elements out of all elements is following given condition then true will be generated
print(np.all(sampleMasking >=5, axis=0))
print(np.all(sampleMasking >=5, axis=1))

[ True  True False False  True]
[ True  True  True]
[ True  True False False False]
[False False False]


In [258]:
sampleExerciseArrayIndexing = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(sampleExerciseArrayIndexing[2:4,0:2])
print(sampleExerciseArrayIndexing[[0,1,2,3],[1,2,3,4]])
print(sampleExerciseArrayIndexing[0,-2:])
print(sampleExerciseArrayIndexing[-2:,-2:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[4 5]
[[24 25]
 [29 30]]
